name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any

  # HTTP
  dio: ^5.7.0

  # Estado
  flutter_riverpod: ^2.6.1

  # Geolocalização
  geolocator: ^13.0.2

  # Variáveis de ambiente (para proteger a API key)
  flutter_dotenv: ^5.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env